sudo: false

language: php

php:
  - 7.0

branches:
  only:
    - master

env:
  - COMPOSER_DISABLE_XDEBUG_WARN=1

cache:
  directories:
    - $TRAVIS_BUILD_DIR/node_modules
    - $TRAVIS_BUILD_DIR/vendor

install:
  - # Disable xdebug to speed up Composer install
  - cp ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini.bak

  - composer install --prefer-dist --no-interaction
  - npm install remark remark-lint

script:
  - # Restore xdebug to gather code coverage
  - cp ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini.bak ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini

  - vendor/bin/phpunit
  - vendor/bin/php-coverage-checker build/coverage-clover.xml 100
  - vendor/bin/phpcs --standard=PSR2 ./src ./test
  - node_modules/remark/bin/remark --no-stdout CHANGELOG.md CONTRIBUTING.md README.md

  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/coverage-clover.xml
